[package]
name = "tcp-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.15.0"
ifstructs = "0.1.1"
libc = "0.2.153"
tun-tap = "0.1.4"
